apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: test-app-ingress
  namespace: {{.Values.namespace}}
spec:
  rules:
  - host: testapp.com
    http:
      paths:
      - backend:
          serviceName: test-svc
          servicePort: 80
        path: /